default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: maino_blog_api_development
  username: maino
  password: beija-flor

test:
  <<: *default
  database: maino_blog_api_test
  username: maino
  password: beija-flor


production:
  <<: *default
  database: maino_blog_api_production
  username: maino_blog_api
  password: <%= ENV["MAINO_BLOG_API_DATABASE_PASSWORD"] %>
